---
- hosts: localhost
  gather_facts: false
  tags: k8s
  tasks:
    - k8s_info:
        api_version: v1
        kind: User
      register: users
      changed_when: false

    - set_fact:
        email_addresses: "{{ users.resources|json_query('[].metadata.name') }}"

- hosts: mailman_servers
  gather_facts: false
  collections:
    - moc.mailman

  tasks:
    - mailman_list:
        name: operate-first-users
        owner: "{{ operate_first_owner }}"
        notify_owner: false
        config:
          default_member_moderation: true
          member_moderation_action: 2
          generic_nonmember_action: 3
          accept_these_nonmembers: "{{ operate_first_posters }}"

    - mailman_list_members:
        name: operate-first-users
        notify_members: false
        notify_admins: false
        members: "{{ hostvars.localhost.email_addresses }}"
      register: result

    - tags: [listinfo]
      mailman_list_info:
        name: operate-first-users
      register: listinfo
